//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int user_friend_id { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
