//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend_request
    {
        public int id { get; set; }
        public int sender_id { get; set; }
        public int receive_user_id { get; set; }
        public int request_status { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
