//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class hobby
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string hobbies { get; set; }
        public string favorite_tv_shows { get; set; }
        public string favorite_movies { get; set; }
        public string favorite_games { get; set; }
        public string favorite_books { get; set; }
        public string favorite_writers { get; set; }
        public string other_interest { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
