//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> post_type { get; set; }
        public string description { get; set; }
        public string media_path { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
